language: python
python:
  - 3.9
  - 3.8
  - 3.7

# what branches should be evaluated
branches:
    only:
        - main

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -q -n test_environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
  - conda activate test_environment
  - python -m pip install .

# the actual commands to run
script:
    - python -m pytest --cov-report term --cov=. tests/

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls